# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Real Estate Updates
email:
description: >- # this means to ignore newlines until "baseurl:"
  This is where updates are posted on the real estate projects ongoing. 
  ##
  ##
#twitter_username: 
#github_username: 
minimal_mistakes_skin: default
url: "https://paper-engineer.github.io"
baseurl: "/real-estate-updates"
repository: "paper-engineer/real-estate-updates"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
exclude: [".gitignore", "LICENSE", "README.md"]
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: NZ # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Mog"
  avatar : "/assets/images/eels.jpg"
  bio    : "This is the real estate side of things. If you're after the Guides to Life, that's the other website, linked below."
  links:
    - label: "Click Here for Guides"
    #  icon: "fas fa-fw fa-link"
      url: "https://guides.alwaysdata.net"
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/"
    #- label: "GitHub"
    #  icon: "fab fa-fw fa-github"
    #  url: "https://github.com/"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"

footer:
  links:
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/"
    #- label: "GitHub"
    #  icon: "fab fa-fw fa-github"
    #  url: "https://github.com/"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"

#collections:
#  site-info:
#    output: true
#    permalink: /:collection/:path/
#  project-info:
#    output: true
#    permalink: /:collection/:path/
#I have decided we are not using collections. 

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: true
      show_date: true
      toc: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _site-info
  #- scope:
  #    path: "_site-info"
  #    type: pages
  #  values:
  #    layout: single
  #    author_profile: true
  #    toc: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

atom_feed:
  hide: true
